-- MySQL Script generated by MySQL Workbench
-- Mon Oct 30 01:44:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema godb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema godb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `godb` DEFAULT CHARACTER SET utf8 ;
USE `godb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `godb`.`User` (
  `id` VARCHAR(255) NOT NULL,
  `username` VARCHAR(128) NOT NULL,
  `firstName` VARCHAR(128) NOT NULL,
  `lastName` VARCHAR(128) NOT NULL,
  `pictureURL` VARCHAR(255) NULL,
  `refreshToken` VARCHAR(255) NOT NULL,
  `accessToken` VARCHAR(255) NOT NULL,
  `registrationDate` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `godb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `godb`.`Account` (
  `id` VARCHAR(255) NOT NULL,
  `refreshToken` VARCHAR(255) NOT NULL,
  `accessToken` VARCHAR(255) NOT NULL,
  `username` VARCHAR(128) NOT NULL,
  `server` VARCHAR(10) NOT NULL,
  `User_id` VARCHAR(255) NOT NULL,
  `registrationDate` DATE NOT NULL,
  PRIMARY KEY (`id`, `server`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Account_User2_idx` (`User_id` ASC),
  CONSTRAINT `fk_Account_User2`
    FOREIGN KEY (`User_id`)
    REFERENCES `godb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
